# Generated by Django 2.1.5 on 2019-02-06 10:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableModel',
            fields=[
                ('id_material', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('consumable', models.CharField(max_length=32)),
                ('variant', models.CharField(max_length=255)),
                ('diameter', models.FloatField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id_printer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand_model', models.CharField(max_length=255)),
                ('layer_precision', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.2], size=None)),
                ('hotend_size', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0.4], size=None)),
                ('x_size', models.IntegerField()),
                ('y_size', models.IntegerField()),
                ('z_size', models.IntegerField()),
                ('dual_extruder', models.BooleanField(default=False)),
                ('heated_bed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SlicerParamsModel',
            fields=[
                ('id_params', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hotend_diameter', models.FloatField()),
                ('layer_resolution', models.IntegerField()),
                ('support', models.BooleanField(default=False)),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pullapp.PrinterModel')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('id_submission', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('stl', models.FileField(upload_to='')),
                ('copies', models.IntegerField(default=0)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('EN ATTENTE', 'En attente'), ('REFUSE', 'Refusé'), ('IMPRESSION', 'Impression'), ('IMPRIME', 'Imprimé')], default='SOUMIS', max_length=10)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pullapp.ConsumableModel')),
            ],
        ),
        migrations.AddField(
            model_name='slicerparamsmodel',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pullapp.SubmissionModel'),
        ),
    ]
